### ISSUE TITLE
couldnt find dll

### ISSUE THREAD

**Issue by Benjjiyy** [ZenixYT/fortnite-fov-changer#1]
yeah, it cant find some dll

**Comment by Benjjiyy** [comment]
or i mean, i couldnt build it either so i had to use the pre compiled and thats the one that doesnt work idk about the otehr

**Comment by denalisun** [comment]
There is no DLL required, this is not an injection process.

**Comment by Benjjiyy** [comment]
dude im not retarded, i know it isnt but when i launch it i get taht error lmfao
